services:
  leetcode__node:
    build: ./docker/images/node
    container_name: leetcode__node
    image: leetcode__node
    tty: true
    ports:
      - 8099:8099
    working_dir: /app
    volumes:
      - ./js:/app
  leetcode__php:
    build: ./docker/images/php
    container_name: leetcode__php
    image: leetcode__php
    tty: true
    ports:
      - 8098:8098
    working_dir: /app
    volumes:
      - ./php:/app
